### ISSUE TITLE
use-async-effect.d.ts not available after installation

### ISSUE THREAD

**Issue by sebasgoldberg** [DigitalBrainJS/use-async-effect#1]
File use-async-effect.d.ts is not available in use-async-effect2 folder inside node_modules, after installation.

Thanks!

**Comment by DigitalBrainJS** [comment]
Just fixed it. Thanks for the report!

**Comment by sebasgoldberg** [comment]
Thanks Dmitriy!

The library was very useful for me, thanks a lot!
